# Generated by Django 5.2.13 on 2026-04-12 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_alter_patient_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
