# Generated by Django 5.2.13 on 2026-04-12 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_patient_is_verified_patient_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='otp',
        ),
    ]
