# Generated by Django 5.2.13 on 2026-05-03 17:37

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_remove_patient_is_verified_remove_patient_otp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('app_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('time', models.TimeField(verbose_name='الوقت')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('confirmed', 'مؤكد'), ('completed', 'اكتمل'), ('cancelled', 'ملغى'), ('no-show', 'لم يحضر')], default='pending', max_length=20, verbose_name='الحالة')),
                ('type', models.CharField(choices=[('online', 'أونلاين'), ('in-person', 'حضوري')], max_length=20, verbose_name='نوع الموعد')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'موعد',
                'verbose_name_plural': 'المواعيد',
                'db_table': 'appointment',
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('availability_id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.CharField(choices=[('saturday', 'السبت'), ('sunday', 'الأحد'), ('monday', 'الإثنين'), ('tuesday', 'الثلاثاء'), ('wednesday', 'الأربعاء'), ('thursday', 'الخميس'), ('friday', 'الجمعة')], max_length=20, verbose_name='اليوم')),
                ('is_open', models.BooleanField(default=False, verbose_name='مفتوح')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='وقت البداية')),
                ('end_time', models.TimeField(verbose_name='وقت الإغلاق')),
                ('online_start_time', models.TimeField(blank=True, null=True, verbose_name='بداية الخدمة الأونلاين')),
                ('online_end_time', models.TimeField(blank=True, null=True, verbose_name='نهاية الخدمة الأونلاين')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'التوفرية',
                'verbose_name_plural': 'التوفريات',
                'db_table': 'availability',
            },
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('clinic_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='اسم العيادة')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$')], verbose_name='رقم الهاتف')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='clinic/', verbose_name='الشعار')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='العنوان')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='خط العرض')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='خط الطول')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'عيادة',
                'verbose_name_plural': 'العيادات',
                'db_table': 'clinic',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('sender', models.CharField(max_length=255, verbose_name='مرسل الرسالة')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('subject', models.CharField(max_length=255, verbose_name='الموضوع')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
                ('reply', models.TextField(blank=True, null=True, verbose_name='الرد')),
                ('reply_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الرد')),
                ('is_read', models.BooleanField(default=False, verbose_name='مقروءة')),
                ('sender_type', models.CharField(choices=[('patient', 'مريض'), ('visitor', 'زائر')], default='visitor', max_length=20, verbose_name='نوع المرسل')),
            ],
            options={
                'verbose_name': 'رسالة',
                'verbose_name_plural': 'الرسائل',
                'db_table': 'message',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('time', models.TimeField(verbose_name='الوقت')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('completed', 'مكتمل'), ('failed', 'فشل'), ('refunded', 'مرجع')], default='pending', max_length=20, verbose_name='الحالة')),
                ('type', models.CharField(choices=[('appointment', 'موعد'), ('product', 'منتج'), ('package', 'باقة'), ('workshop', 'ورشة عمل')], max_length=50, verbose_name='النوع')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='طريقة الدفع')),
                ('transaction_id', models.CharField(blank=True, max_length=255, unique=True, verbose_name='معرف المعاملة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'دفعة',
                'verbose_name_plural': 'الدفعات',
                'db_table': 'payment',
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='WorkshopSubscription',
            fields=[
                ('workshop_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('time', models.TimeField(verbose_name='الوقت')),
                ('place', models.CharField(blank=True, max_length=255, verbose_name='المكان')),
                ('type', models.CharField(choices=[('online', 'أونلاين'), ('in-person', 'حضوري')], max_length=20, verbose_name='النوع')),
                ('overview', models.TextField(verbose_name='النبذة')),
                ('img', models.ImageField(blank=True, null=True, upload_to='workshops/', verbose_name='الصورة')),
                ('link', models.URLField(blank=True, null=True, verbose_name='الرابط')),
                ('status', models.CharField(choices=[('upcoming', 'قادمة'), ('ongoing', 'جارية'), ('completed', 'اكتملت'), ('cancelled', 'ملغاة')], default='upcoming', max_length=20, verbose_name='الحالة')),
                ('num_participants', models.IntegerField(default=0, verbose_name='عدد المشاركين')),
                ('max_participants', models.IntegerField(blank=True, null=True, verbose_name='الحد الأقصى للمشاركين')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'اشتراك ورشة عمل',
                'verbose_name_plural': 'اشتراكات ورش العمل',
                'db_table': 'workshop_subscription',
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.RemoveField(
            model_name='lab',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='order',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='package',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='packages',
        ),
        migrations.AlterModelOptions(
            name='educationalpublication',
            options={'ordering': ['-created_at'], 'verbose_name': 'منشور تعليمي', 'verbose_name_plural': 'المنشورات التعليمية'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-time'], 'verbose_name': 'إشعار', 'verbose_name_plural': 'الإشعارات'},
        ),
        migrations.AlterModelOptions(
            name='nutritionist',
            options={'ordering': ['-created_at'], 'verbose_name': 'أخصائي تغذية', 'verbose_name_plural': 'أخصائيو التغذية'},
        ),
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['-created_at'], 'verbose_name': 'باقة', 'verbose_name_plural': 'الباقات'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['-created_at'], 'verbose_name': 'مريض', 'verbose_name_plural': 'المرضى'},
        ),
        migrations.AlterModelOptions(
            name='patientworkshop',
            options={'ordering': ['patient'], 'verbose_name': 'اشتراك ورشة', 'verbose_name_plural': 'اشتراكات الورش'},
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['-upload_at'], 'verbose_name': 'خطة غذائية', 'verbose_name_plural': 'الخطط الغذائية'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'منتج', 'verbose_name_plural': 'المنتجات'},
        ),
        migrations.AlterModelOptions(
            name='workshop',
            options={'ordering': ['-date', '-time'], 'verbose_name': 'ورشة عمل', 'verbose_name_plural': 'ورش العمل'},
        ),
        migrations.RemoveField(
            model_name='educationalpublication',
            name='content_id',
        ),
        migrations.RemoveField(
            model_name='educationalpublication',
            name='publication_date',
        ),
        migrations.RemoveField(
            model_name='educationalpublication',
            name='type',
        ),
        migrations.RemoveField(
            model_name='educationalpublication',
            name='views_number',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='content',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='noti_id',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='state',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='type',
        ),
        migrations.RemoveField(
            model_name='nutritionist',
            name='email',
        ),
        migrations.RemoveField(
            model_name='nutritionist',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='nutritionist',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='nutritionist',
            name='nut_id',
        ),
        migrations.RemoveField(
            model_name='nutritionist',
            name='password',
        ),
        migrations.RemoveField(
            model_name='package',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='email',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='nutritionist',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='password',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='patient_id',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='workshops',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='content',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='location',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='max_number',
        ),
        migrations.AddField(
            model_name='educationalpublication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='educationalpublication',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='publications/', verbose_name='الصورة'),
        ),
        migrations.AddField(
            model_name='educationalpublication',
            name='last_sentence',
            field=models.CharField(blank=True, max_length=255, verbose_name='الجملة الأخيرة'),
        ),
        migrations.AddField(
            model_name='educationalpublication',
            name='overview',
            field=models.TextField(default='', verbose_name='النبذة'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='educationalpublication',
            name='publication_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='educationalpublication',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ النشر'),
        ),
        migrations.AddField(
            model_name='educationalpublication',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('published', 'منشورة'), ('archived', 'مؤرشفة')], default='draft', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AddField(
            model_name='educationalpublication',
            name='title',
            field=models.CharField(default='', max_length=255, verbose_name='العنوان'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='educationalpublication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='info',
            field=models.TextField(default='', verbose_name='المعلومات'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('unread', 'غير مقروءة'), ('read', 'مقروءة'), ('archived', 'مؤرشفة')], default='unread', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AddField(
            model_name='notification',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='الوقت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nutritionist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nutritionist',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='nutritionist',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AddField(
            model_name='nutritionist',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='nutritionists/', verbose_name='صورة الملف'),
        ),
        migrations.AddField(
            model_name='nutritionist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='nutritionist',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='nutritionist_profile', to=settings.AUTH_USER_MODEL, verbose_name='حساب المستخدم'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='category',
            field=models.CharField(choices=[('medical', 'إجراءات طبية'), ('diet', 'حمية غذائية')], default=1, max_length=20, verbose_name='نوع الباقة'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='details',
            field=models.TextField(default='', verbose_name='مميزات الباقة'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='first_payment_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='نسبة الدفعة الأولى'),
        ),
        migrations.AddField(
            model_name='package',
            name='num',
            field=models.IntegerField(default=0, verbose_name='مدة الباقة (بالشهور)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='require_consultation',
            field=models.BooleanField(default=False, verbose_name='استشارة مسبقة'),
        ),
        migrations.AddField(
            model_name='package',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='birth_date',
            field=models.DateField(default='2000-01-01', verbose_name='تاريخ الميلاد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AddField(
            model_name='patient',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='patients/', verbose_name='صورة الملف'),
        ),
        migrations.AddField(
            model_name='patient',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='description',
            field=models.TextField(blank=True, verbose_name='الوصف'),
        ),
        migrations.AddField(
            model_name='plan',
            name='file',
            field=models.FileField(default='', upload_to='plans/', verbose_name='الملف'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='nutritionist',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='clinic.nutritionist', verbose_name='أخصائي التغذية'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر تحديث'),
        ),
        migrations.AddField(
            model_name='plan',
            name='upload_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاريخ الرفع'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='الوصف'),
        ),
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(default='', upload_to='products/', verbose_name='الصورة'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='متاح'),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('herbal', 'عشبية صحية'), ('tools', 'أدوات الصحة'), ('snacks', 'سناكات صحية')], default='', max_length=50, verbose_name='النوع'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workshop',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='workshops/', verbose_name='الصورة'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='الرابط'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='max_participants',
            field=models.IntegerField(blank=True, null=True, verbose_name='الحد الأقصى للمشاركين'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='num_participants',
            field=models.IntegerField(default=0, verbose_name='عدد المشاركين'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='overview',
            field=models.TextField(default='', verbose_name='النبذة'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workshop',
            name='place',
            field=models.CharField(blank=True, max_length=255, verbose_name='المكان'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='status',
            field=models.CharField(choices=[('upcoming', 'قادمة'), ('ongoing', 'جارية'), ('completed', 'اكتملت'), ('cancelled', 'ملغاة')], default='upcoming', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='time',
            field=models.TimeField(default='00:00:00', verbose_name='الوقت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workshop',
            name='type',
            field=models.CharField(choices=[('online', 'أونلاين'), ('in-person', 'حضوري')], default='', max_length=20, verbose_name='النوع'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workshop',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='educationalpublication',
            name='content',
            field=models.TextField(verbose_name='المحتوى'),
        ),
        migrations.AlterField(
            model_name='educationalpublication',
            name='nutritionist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='clinic.nutritionist', verbose_name='أخصائي التغذية'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='clinic.patient', verbose_name='المريض'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=255, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='nutritionist',
            name='overview',
            field=models.TextField(blank=True, verbose_name='نبذة'),
        ),
        migrations.AlterField(
            model_name='nutritionist',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$')], verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='nutritionist',
            name='specialization',
            field=models.CharField(max_length=255, verbose_name='التخصص'),
        ),
        migrations.AlterField(
            model_name='package',
            name='name',
            field=models.CharField(max_length=255, verbose_name='اسم الباقة'),
        ),
        migrations.AlterField(
            model_name='package',
            name='nutritionist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='clinic.nutritionist', verbose_name='أخصائي التغذية'),
        ),
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الباقة'),
        ),
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.BooleanField(default=True, verbose_name='نشطة'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.CharField(max_length=255, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('male', 'ذكر'), ('female', 'أنثى'), ('other', 'آخر')], max_length=10, verbose_name='الجنس'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$')], verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='patientworkshop',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop_registrations', to='clinic.patient'),
        ),
        migrations.AlterField(
            model_name='patientworkshop',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='clinic.workshop'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='clinic.patient', verbose_name='المريض'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='اسم المنتج'),
        ),
        migrations.AlterField(
            model_name='product',
            name='nutritionist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='clinic.nutritionist', verbose_name='أخصائي التغذية'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(verbose_name='الكمية'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='date',
            field=models.DateField(verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='nutritionist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshops', to='clinic.nutritionist', verbose_name='أخصائي التغذية'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='title',
            field=models.CharField(max_length=255, verbose_name='العنوان'),
        ),
        migrations.AddIndex(
            model_name='educationalpublication',
            index=models.Index(fields=['nutritionist', 'status'], name='educational_nutriti_0c43ab_idx'),
        ),
        migrations.AddIndex(
            model_name='educationalpublication',
            index=models.Index(fields=['published_at'], name='educational_publish_373c26_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['patient', 'status'], name='notificatio_patient_d3ea27_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['user'], name='patient_user_id_ca6b36_idx'),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['patient', 'nutritionist'], name='plan_patient_1de624_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['nutritionist'], name='product_nutriti_881145_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_available'], name='product_is_avai_451bf8_idx'),
        ),
        migrations.AddIndex(
            model_name='workshop',
            index=models.Index(fields=['nutritionist', 'date'], name='workshop_nutriti_355f17_idx'),
        ),
        migrations.AddIndex(
            model_name='workshop',
            index=models.Index(fields=['status'], name='workshop_status_2c3f52_idx'),
        ),
        migrations.AlterModelTable(
            name='educationalpublication',
            table='educational_publication',
        ),
        migrations.AlterModelTable(
            name='notification',
            table='notification',
        ),
        migrations.AlterModelTable(
            name='nutritionist',
            table='nutritionist',
        ),
        migrations.AlterModelTable(
            name='package',
            table='package',
        ),
        migrations.AlterModelTable(
            name='patient',
            table='patient',
        ),
        migrations.AlterModelTable(
            name='patientworkshop',
            table='patient_workshop',
        ),
        migrations.AlterModelTable(
            name='plan',
            table='plan',
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
        migrations.AlterModelTable(
            name='workshop',
            table='workshop',
        ),
        migrations.AddField(
            model_name='appointment',
            name='nutritionist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='clinic.nutritionist', verbose_name='أخصائي التغذية'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='clinic.patient', verbose_name='المريض'),
        ),
        migrations.AddField(
            model_name='availability',
            name='nutritionist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='clinic.nutritionist', verbose_name='أخصائي التغذية'),
        ),
        migrations.AddIndex(
            model_name='clinic',
            index=models.Index(fields=['email'], name='clinic_email_9ffeb3_idx'),
        ),
        migrations.AddField(
            model_name='availability',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='clinic.clinic', verbose_name='العيادة'),
        ),
        migrations.AddField(
            model_name='nutritionist',
            name='clinic',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='nutritionists', to='clinic.clinic', verbose_name='العيادة'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='nutritionist',
            index=models.Index(fields=['user'], name='nutritionis_user_id_2013ee_idx'),
        ),
        migrations.AddIndex(
            model_name='nutritionist',
            index=models.Index(fields=['clinic'], name='nutritionis_clinic__3f9f20_idx'),
        ),
        migrations.AddField(
            model_name='message',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.patient', verbose_name='المريض (إن وجد)'),
        ),
        migrations.AddField(
            model_name='payment',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='clinic.appointment', verbose_name='الموعد'),
        ),
        migrations.AddField(
            model_name='payment',
            name='nutritionist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='clinic.nutritionist', verbose_name='أخصائي التغذية'),
        ),
        migrations.AddField(
            model_name='payment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='clinic.patient', verbose_name='المريض'),
        ),
        migrations.AddField(
            model_name='workshopsubscription',
            name='nutritionist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop_subscriptions', to='clinic.nutritionist', verbose_name='أخصائي التغذية'),
        ),
        migrations.DeleteModel(
            name='Lab',
        ),
        migrations.DeleteModel(
            name='Measurement',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['patient', 'date'], name='appointment_patient_3f30c5_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['nutritionist', 'status'], name='appointment_nutriti_1ffeb6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('patient', 'nutritionist', 'date', 'time')},
        ),
        migrations.AddIndex(
            model_name='availability',
            index=models.Index(fields=['clinic', 'nutritionist'], name='availabilit_clinic__672761_idx'),
        ),
        migrations.AddIndex(
            model_name='availability',
            index=models.Index(fields=['day'], name='availabilit_day_be7c53_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='availability',
            unique_together={('clinic', 'nutritionist', 'day')},
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['email'], name='message_email_9e980f_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_read'], name='message_is_read_8eefe1_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['patient', 'status'], name='payment_patient_ac8b46_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['transaction_id'], name='payment_transac_9ff03c_idx'),
        ),
        migrations.AddIndex(
            model_name='workshopsubscription',
            index=models.Index(fields=['nutritionist', 'date'], name='workshop_su_nutriti_58442d_idx'),
        ),
        migrations.AddIndex(
            model_name='workshopsubscription',
            index=models.Index(fields=['status'], name='workshop_su_status_d94c1e_idx'),
        ),
    ]
