# Generated by Django 5.2.13 on 2026-05-04 17:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_appointment_availability_clinic_message_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='clinic',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='الرجاء إدخال رقم هاتف دولي صالح', regex='^\\+?[1-9]\\d{7,14}$')], verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='nutritionist',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='الرجاء إدخال رقم هاتف دولي صالح', regex='^\\+?[1-9]\\d{7,14}$')], verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='الرجاء إدخال رقم هاتف دولي صالح', regex='^\\+?[1-9]\\d{7,14}$')], verbose_name='رقم الهاتف'),
        ),
    ]
