# Generated by Django 5.2.13 on 2026-05-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_remove_patient_is_active_alter_clinic_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AddField(
            model_name='patient',
            name='height',
            field=models.FloatField(default=0.0, verbose_name='الطول'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='start_weight',
            field=models.FloatField(default=0.0, verbose_name='الوزن عند البدء'),
            preserve_default=False,
        ),
    ]
