# Generated by Django 5.2.13 on 2026-05-04 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0007_patient_email_patient_height_patient_start_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientInitialInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_goal', models.CharField(blank=True, max_length=255)),
                ('followed_diet_before', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, choices=[('child', 'طفل'), ('vegetarian', 'نباتي'), ('pregnant', 'حامل'), ('breastfeeding', 'مرضع')], max_length=50)),
                ('favorite_color', models.CharField(blank=True, max_length=100)),
                ('surgeries', models.TextField(blank=True)),
                ('last_analysis', models.TextField(blank=True)),
                ('doctor_diagnosis', models.TextField(blank=True)),
                ('visit_purpose', models.TextField(blank=True)),
                ('medications', models.TextField(blank=True)),
                ('has_pressure', models.BooleanField(default=False)),
                ('has_diabetes', models.BooleanField(default=False)),
                ('has_cholesterol', models.BooleanField(default=False)),
                ('has_colon', models.BooleanField(default=False)),
                ('has_constipation', models.BooleanField(default=False)),
                ('has_thyroid', models.BooleanField(default=False)),
                ('has_food_allergy', models.BooleanField(default=False)),
                ('has_pcos', models.BooleanField(default=False)),
                ('has_irregular_period', models.BooleanField(default=False)),
                ('takes_cortisone', models.BooleanField(default=False)),
                ('takes_birth_control', models.BooleanField(default=False)),
                ('takes_allergy_med', models.BooleanField(default=False)),
                ('takes_glucose_regulator', models.BooleanField(default=False)),
                ('takes_cycle_regulator', models.BooleanField(default=False)),
                ('takes_retan', models.BooleanField(default=False)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='initial_info', to='clinic.patient')),
            ],
        ),
    ]
